{
 "title": "Prova de Concepte",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura Cubell 0 (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 0\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor XXXX\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura(ºC)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Temperatura Cubell 1 (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 1\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor XXXX\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura(ºC)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Temperatura Cubell 2 (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 2\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor XXXX\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Temperatura(ºC)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Acidesa Cubell 0 (pH)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 0\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor YYYY\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Acidesa(pH)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Acidesa Cubell 1 (pH)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 1\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor YYYY\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Acidesa(pH)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Acidesa Cubell 2 (pH)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 2\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor YYYY\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Acidesa(pH)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Pressió Cubell 0 (Pa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 0\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor ZZZZ\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Presió(Pa)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Pressió Cubell 1 (Pa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 1\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor ZZZZ\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Presió(Pa)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  },
  {
   "title": "Pressió Cubell 2 (Pa)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"Sensors\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Cubell 2\")\n  |> filter(fn: (r) => r[\"Sensor\"] == \"Sensor ZZZZ\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Presió(Pa)\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"unique\")"
    }
   ]
  }
 ]
}